version: '3'
services:
  postgresql:
    image: postgres:9.5-alpine
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      timeout: 45s
      interval: 10s
      retries: 10
    restart: always
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
    volumes:
      - ./deployments/docker/scripts/db:/docker-entrypoint-initdb.d/

  vault:
    image: vault:0.9.3
    ports:
      - 8200:8200
    environment:
      - SKIP_SETCAP=1
      - VAULT_DEV_ROOT_TOKEN_ID=8fb95528-57c6-422e-9722-d2147bcba8ed
      - VAULT_ADDR=http://localhost:8200

  accountapi:
    image: form3tech/interview-accountapi:v1.0.0-4-g63cf8434
    ports:
      - 8080:8080
    restart: on-failure
    depends_on:
      - postgresql
      - vault
    environment:
      - GIN_MODE=debug
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=8fb95528-57c6-422e-9722-d2147bcba8ed
      - PSQL_USER=root
      - PSQL_PASSWORD=password
      - PSQL_HOST=postgresql
      - PSQL_PORT=5432
      - STACK_NAME=f3-interview-accountapi
      - DATABASE-HOST=postgresql
      - DATABASE-SSL-MODE=disable
      - DATABASE-USERNAME=interview_accountapi_user
      - DATABASE-PASSWORD=123

  accountapiclient:
    build:
      context: .
      dockerfile: Dockerfile
    image: pancudaniel7/fake-api-client:v1.0.0
    depends_on:
      - accountapi
    environment:
      - BASE_API_URL=http://accountapi:8080/v1
      - HTTP_RECORD_VERSION=0
      - HTTP_DEFAULT_PAGE_SIZE=2